#!/usr/bin/env bash
set -euo pipefail

DOTFILES_DIR="$(cd "$(dirname "$0")" && pwd)"
CONFIG_FILE="$DOTFILES_DIR/config.env"
source "$DOTFILES_DIR/packages.sh"

# Check for stow
if ! command -v stow &>/dev/null; then
    echo "GNU Stow is required but not installed."
    echo "Install it with: sudo apt install stow"
    exit 1
fi

# Load config
if [ ! -f "$CONFIG_FILE" ]; then
    echo "Missing config.env — copy the example and fill it in:"
    echo "  cp config.env.example config.env"
    exit 1
fi
source "$CONFIG_FILE"

# The stow --adopt loop below is followed by `git checkout -- .`, which discards
# every uncommitted change to a tracked file. Stop here so local work survives.
if ! git -C "$DOTFILES_DIR" diff --quiet; then
    echo "The dotfiles repository has uncommitted changes to tracked files:"
    git -C "$DOTFILES_DIR" diff --name-only | sed 's/^/  /'
    echo "install.sh would discard them. Commit or stash them first."
    exit 1
fi

# If no custom lockscreen, link the example
LOCKSCREEN="$DOTFILES_DIR/swaylock/.config/swaylock/img/lockscreen.png"
if [ ! -f "$LOCKSCREEN" ]; then
    echo "No lockscreen.png found, linking example..."
    ln -s lockscreen.png.example "$LOCKSCREEN"
fi

echo "Backing up existing files that would be overwritten..."

BACKUP_TIMESTAMP=$(date +%Y%m%d_%H%M%S)
BACKUP_DIR="$DOTFILES_DIR/backups/$BACKUP_TIMESTAMP"
backed_up=0

for pkg in "${PACKAGES[@]}"; do
    if [ -d "$DOTFILES_DIR/$pkg" ]; then
        # Find all target files/dirs this package would create in $HOME
        while IFS= read -r rel_path; do
            target="$HOME/$rel_path"
            if [ -e "$target" ] || [ -L "$target" ]; then
                mkdir -p "$BACKUP_DIR/$(dirname "$rel_path")"
                # Dereference symlinks so backups are always real files
                cp -rL "$target" "$BACKUP_DIR/$rel_path"
                echo "  backed up: ~/$rel_path"
                backed_up=1
            fi
        done < <(cd "$DOTFILES_DIR/$pkg" && find . -type f | sed 's|^\./||')
    fi
done

if [ "$backed_up" -eq 1 ]; then
    echo "Backups saved to: $BACKUP_DIR"
else
    echo "  (no existing files to back up)"
    rmdir "$BACKUP_DIR" 2>/dev/null || true
fi

echo ""
echo "Stowing dotfiles from $DOTFILES_DIR"

for pkg in "${PACKAGES[@]}"; do
    if [ -d "$DOTFILES_DIR/$pkg" ]; then
        echo "  -> $pkg"
        stow -d "$DOTFILES_DIR" -t "$HOME" --adopt "$pkg"
    else
        echo "  !! $pkg not found, skipping"
    fi
done

# After --adopt, stow pulls existing files into the repo.
# Reset any adopted changes to keep repo contents authoritative.
echo ""
echo "Restoring repo state (undoing any adopted diffs)..."
git -C "$DOTFILES_DIR" checkout -- .

# Seed the live wallpaper from the tracked default only if none exists yet.
# wallpaper.png is gitignored, so pull/checkout never clobber a custom wallpaper;
# a fresh clone gets the default, an existing squirrel is left untouched.
WALLPAPER="$DOTFILES_DIR/cwc/.config/cwc/wallpaper.png"
WALLPAPER_DEFAULT="$DOTFILES_DIR/cwc/.config/cwc/wallpaper.png.default"
if [ ! -f "$WALLPAPER" ] && [ -f "$WALLPAPER_DEFAULT" ]; then
    echo "No wallpaper.png found, seeding from default..."
    cp "$WALLPAPER_DEFAULT" "$WALLPAPER"
fi

# Replace placeholders in the git configs after checkout. These two files are
# marked skip-worktree, so rewriting them in place does not dirty the repository.
echo "Applying config..."
sed -i "s|{{WORK_GIT_NAME}}|$WORK_GIT_NAME|g; s|{{WORK_GIT_EMAIL}}|$WORK_GIT_EMAIL|g" "$DOTFILES_DIR/git/.gitconfig"
sed -i "s|{{PERSONAL_GIT_NAME}}|$PERSONAL_GIT_NAME|g; s|{{PERSONAL_GIT_EMAIL}}|$PERSONAL_GIT_EMAIL|g" "$DOTFILES_DIR/git/.gitconfig-personal"

# The shell rc files are tracked and edited often, so they must not be rewritten
# in place. Write the machine-specific values to a generated file outside the
# repository instead. .zshrc and .bashrc source this file if it exists.
LOCAL_ENV="$HOME/.config/dotfiles/env.sh"
mkdir --parents "$(dirname "$LOCAL_ENV")"
cat > "$LOCAL_ENV" <<EOF
# Generated by install.sh from config.env. Do not edit by hand.
export CYCLONEDDS_URI="$CYCLONEDDS_URI"
EOF

# Optional: Awesome WM
read -rp "Set up Awesome WM config? [y/N] " awesome_answer
if [[ "${awesome_answer,,}" == "y" ]]; then
    AWESOME_DIR="$HOME/.config/awesome"

    if [ ! -d "$AWESOME_DIR/.git" ]; then
        echo "Cloning awesome-copycats..."
        git clone --recurse-submodules https://github.com/lcpz/awesome-copycats "$AWESOME_DIR"
    else
        echo "awesome-copycats already cloned, skipping."
    fi

    # Back up awesome files that stow will overwrite
    while IFS= read -r rel_path; do
        target="$HOME/$rel_path"
        if [ -e "$target" ] || [ -L "$target" ]; then
            mkdir -p "$BACKUP_DIR/$(dirname "$rel_path")"
            cp -rL "$target" "$BACKUP_DIR/$rel_path"
            echo "  backed up: ~/$rel_path"
        fi
    done < <(cd "$DOTFILES_DIR/awesome" && find . -type f | sed 's|^\./||')

    # Stow our customizations on top of the cloned repo
    echo "  -> awesome (overlay)"
    stow -d "$DOTFILES_DIR" -t "$HOME" --adopt awesome
    git -C "$DOTFILES_DIR" checkout -- awesome

    # If no custom wallpaper, fall back to the backup
    AWESOME_WALL="$AWESOME_DIR/themes/powerarrow-dark/wall.jpg"
    if [ ! -f "$AWESOME_WALL" ] || [ -L "$AWESOME_WALL" ]; then
        echo "No wall.jpg found, linking backup..."
        ln -sf wall.jpg.bak "$AWESOME_WALL"
    fi

    # Silence stow-managed files in the cloned repo's git status
    git -C "$AWESOME_DIR" update-index --assume-unchanged rc.lua 2>/dev/null || true
    git -C "$AWESOME_DIR" update-index --assume-unchanged themes/powerarrow-dark/theme.lua 2>/dev/null || true
fi

echo ""
echo "Done! All packages stowed."
