#!/usr/bin/env bash
set -euo pipefail

DOTFILES_DIR="$(cd "$(dirname "$0")" && pwd)"
CONFIG_FILE="$DOTFILES_DIR/config.env"
source "$DOTFILES_DIR/packages.sh"

if ! command -v stow &>/dev/null; then
    echo "GNU Stow is required but not installed."
    echo "Install it with: sudo apt install stow"
    exit 1
fi

if [ ! -f "$CONFIG_FILE" ]; then
    echo "Missing config.env — copy the example and fill it in:"
    echo "  cp config.env.example config.env"
    exit 1
fi
source "$CONFIG_FILE"

LOCKSCREEN="$DOTFILES_DIR/swaylock/.config/swaylock/img/lockscreen.png"
if [ ! -f "$LOCKSCREEN" ]; then
    echo "No lockscreen.png found, linking example..."
    ln -s lockscreen.png.example "$LOCKSCREEN"
fi

echo "Backing up existing files that would be overwritten..."

BACKUP_TIMESTAMP=$(date +%Y%m%d_%H%M%S)
BACKUP_DIR="$DOTFILES_DIR/backups/$BACKUP_TIMESTAMP"
backed_up=0

for pkg in "${PACKAGES[@]}"; do
    if [ -d "$DOTFILES_DIR/$pkg" ]; then
        while IFS= read -r rel_path; do
            target="$HOME/$rel_path"
            if [ -e "$target" ] || [ -L "$target" ]; then
                mkdir -p "$BACKUP_DIR/$(dirname "$rel_path")"
                cp -rL "$target" "$BACKUP_DIR/$rel_path"
                echo "  backed up: ~/$rel_path"
                backed_up=1
            fi
        done < <(cd "$DOTFILES_DIR/$pkg" && find . -type f | sed 's|^\./||')
    fi
done

if [ "$backed_up" -eq 1 ]; then
    echo "Backups saved to: $BACKUP_DIR"
else
    echo "  (no existing files to back up)"
    rmdir "$BACKUP_DIR" 2>/dev/null || true
fi

echo ""
echo "Stowing dotfiles from $DOTFILES_DIR"

for pkg in "${PACKAGES[@]}"; do
    if [ -d "$DOTFILES_DIR/$pkg" ]; then
        echo "  -> $pkg"
        stow -d "$DOTFILES_DIR" -t "$HOME" --adopt "$pkg"
    else
        echo "  !! $pkg not found, skipping"
    fi
done

echo ""
echo "Restoring repo state (undoing any adopted diffs)..."
git -C "$DOTFILES_DIR" checkout -- .

WALLPAPER="$DOTFILES_DIR/cwc/.config/cwc/wallpaper.png"
WALLPAPER_DEFAULT="$DOTFILES_DIR/cwc/.config/cwc/wallpaper.png.default"
if [ ! -f "$WALLPAPER" ] && [ -f "$WALLPAPER_DEFAULT" ]; then
    echo "No wallpaper.png found, seeding from default..."
    cp "$WALLPAPER_DEFAULT" "$WALLPAPER"
fi

echo "Applying config..."
sed -i "s|{{WORK_GIT_NAME}}|$WORK_GIT_NAME|g; s|{{WORK_GIT_EMAIL}}|$WORK_GIT_EMAIL|g" "$DOTFILES_DIR/git/.gitconfig"
sed -i "s|{{PERSONAL_GIT_NAME}}|$PERSONAL_GIT_NAME|g; s|{{PERSONAL_GIT_EMAIL}}|$PERSONAL_GIT_EMAIL|g" "$DOTFILES_DIR/git/.gitconfig-personal"

mkdir -p "$HOME/.config/dotfiles"
cat > "$HOME/.config/dotfiles/env.sh" <<'EOF'
# Generated by install.sh from config.env. Do not edit by hand.
ROS_WORKSPACE="{{ROS_WORKSPACE}}"

_dds_rc=$(find "$ROS_WORKSPACE/.direnv" -maxdepth 1 -name 'flake-profile-*.rc' -printf '%T@ %p\n' 2>/dev/null | sort -rn | head -n 1 | cut -d' ' -f2-)
_dds_uri=""
[ -n "$_dds_rc" ] && _dds_uri=$(sed -n "s/^CYCLONEDDS_URI='\(.*\)'/\1/p" "$_dds_rc" | head -n 1)

if [ -n "$_dds_uri" ] && [ -f "${_dds_uri#file://}" ]; then
    export CYCLONEDDS_URI="$_dds_uri"
elif [ -n "${CYCLONEDDS_URI:-}" ] && [ ! -f "${CYCLONEDDS_URI#file://}" ]; then
    unset CYCLONEDDS_URI
fi
unset _dds_rc _dds_uri

export RMW_IMPLEMENTATION="${RMW_IMPLEMENTATION:-rmw_cyclonedds_cpp}"
EOF
sed -i "s|{{ROS_WORKSPACE}}|$ROS_WORKSPACE|g" "$HOME/.config/dotfiles/env.sh"

read -rp "Set up Awesome WM config? [y/N] " awesome_answer
if [[ "${awesome_answer,,}" == "y" ]]; then
    AWESOME_DIR="$HOME/.config/awesome"

    if [ ! -d "$AWESOME_DIR/.git" ]; then
        echo "Cloning awesome-copycats..."
        git clone --recurse-submodules https://github.com/lcpz/awesome-copycats "$AWESOME_DIR"
    else
        echo "awesome-copycats already cloned, skipping."
    fi

    while IFS= read -r rel_path; do
        target="$HOME/$rel_path"
        if [ -e "$target" ] || [ -L "$target" ]; then
            mkdir -p "$BACKUP_DIR/$(dirname "$rel_path")"
            cp -rL "$target" "$BACKUP_DIR/$rel_path"
            echo "  backed up: ~/$rel_path"
        fi
    done < <(cd "$DOTFILES_DIR/awesome" && find . -type f | sed 's|^\./||')

    echo "  -> awesome (overlay)"
    stow -d "$DOTFILES_DIR" -t "$HOME" --adopt awesome
    git -C "$DOTFILES_DIR" checkout -- awesome

    AWESOME_WALL="$AWESOME_DIR/themes/powerarrow-dark/wall.jpg"
    if [ ! -f "$AWESOME_WALL" ] || [ -L "$AWESOME_WALL" ]; then
        echo "No wall.jpg found, linking backup..."
        ln -sf wall.jpg.bak "$AWESOME_WALL"
    fi

    git -C "$AWESOME_DIR" update-index --assume-unchanged rc.lua 2>/dev/null || true
    git -C "$AWESOME_DIR" update-index --assume-unchanged themes/powerarrow-dark/theme.lua 2>/dev/null || true
fi

echo ""
echo "Done! All packages stowed."
