background_opacity 0.75
dynamic_background_opacity yes
allow_remote_control yes
listen_on unix:/tmp/kitty-{kitty_pid}

tab_title_max_length 30
tab_title_template "{(d := ('~' if re.fullmatch('/home/[^/]+', wd) else wd.rsplit('/', 1)[-1] or '/') if (wd := tab.active_wd) else '')[:0]}{title if not d or re.search('(^|[/:])' + re.escape(d) + '$', title) else d + ': ' + title}"

include current-theme.conf
